

keycloak.oidc.providerURI=${KEYCLOAK_PROVIDER_URI}
keycloak.oidc.clientId=${KEYCLOAK_CLIENT_ID}
keycloak.oidc.clientSecret=${KEYCLOAK_CLIENT_SECRET}
rbac-api/mp-rest/url=${RBAC_API_URL}
multitenant-api/mp-rest/url=${MULTITENANT_API_URL}
keycloak-login/mp-rest/url=${KEYCLOAK_TOKEN_URL}
